[colors.primary]
background = '#CDE3C8'
foreground = '#3C6746'

[colors.cursor]
text   = '#CDE3C8'
cursor = '#3C6746'

[colors.selection]
text       = '#3C6746'
background = '#B4E1B2'

[colors.normal]
black   = '#CDE3C8'
red     = '#971015'
green   = '#5E800E'
yellow  = '#BF7021'
blue    = '#4F8FA1'
magenta = '#913069'
cyan    = '#BF442B'
white   = '#7A8386'

[colors.bright]
black   = '#73A08D'
red     = '#971015'
green   = '#5E800E'
yellow  = '#BF7021'
blue    = '#4F8FA1'
magenta = '#913069'
cyan    = '#BF442B'
white   = '#1D4E27'
