local M = {}

function M.get(c, opts)
  -- stylua: ignore  
	return {
    Foo                         = { bg = c.magenta2, fg = c.fg },

    Comment                     = { fg = c.green, italic = opts.italic_comments },
    ColorColumn                 = { bg = c.statusbar },
    Conceal                     = { fg = c.statusbar },
    Cursor                      = { fg = c.bg, bg = c.fg },
    lCursor                     = { fg = c.bg, bg = c.fg },
    CursorIM                    = { fg = c.bg, bg = c.fg },
    CursorColumn                = { bg = c.cursorline },
    CursorLine                  = { bg = c.cursorline },
    Directory                   = { fg = c.lightgreen },
    DiffAdd                     = { },
    DiffChange                  = { },
    DiffDelete                  = { },
    DiffText                    = { },
    EndOfBuffer                 = { fg = c.bg },
    ErrorMsg                    = { fg = c.red },
    VertSplit                   = { fg = c.separator },
    WinSeparator                = { fg = c.separator, bold = true },
    Folded                      = { fg = c.blue, bg = c.fg_gutter },
    FoldColumn                  = { bg = c.bg, fg = c.comment },
    SignColumn                  = {},
    SignColumnSB                = {},
    Substitute                  = { bg = c.red, fg = c.black },
    LineNr                      = { fg = "#444444", bg = c.bg },
    CursorLineNr                = { fg = c.yellow, bg = c.bg, bold = true },
    -- LineNrAbove                 = {  },
    -- LineNrBelow                 = {  },
    MatchParen                  = { fg = c.red, bold = true },
    ModeMsg                     = { fg = c.fg, bold = true },
    MsgArea                     = { fg = c.fg },
    MoreMsg                     = { fg = c.blue },
    NonText                     = { fg = c.statusbar },
    Normal                      = { fg = c.fg, bg = c.bg },
    NormalNC                    = { fg = c.fg, bg = c.bg },
    NormalSB                    = { fg = c.fg, bg = c.bg },
    NormalFloat                 = { fg = c.fg, bg = c.separator },
    FloatBorder                 = { fg = c.separator, bg = c.separator },
    FloatTitle                  = { fg = c.separator, bg = c.statusbar },
    Pmenu                       = { bg = c.statusbar, fg = c.fg },
    PmenuMatch                  = { bg = c.cursorline, fg = c.blue },
    PmenuSel                    = { bg = c.cursorline },
    PmenuMatchSel               = { bg = c.cursorline },
    PmenuSbar                   = { bg = c.separator },
    PmenuThumb                  = { bg = c.bg_visual },
    Question                    = { fg = c.blue },
    QuickFixLine                = { bg = c.bg_visual, bold = true },
    Search                      = { bg = c.lightgreen, fg = c.bg },
    IncSearch                   = { bg = c.orange, fg = c.bg },
    CurSearch                   =  "IncSearch",
    SpecialKey                  = { fg = c.dark3 },
    SpellBad                    = { sp = c.red, underline = true },
    SpellCap                    = { sp = c.yellow0, underline = true },
    SpellLocal                  = { sp = c.info, underline = true },
    SpellRare                   = { sp = c.hint, underline = true },
    StatusLine                  = { fg = c.fg, bg = c.statusbar },
    StatusLineNC                = { fg = c.gray, bg = c.bg },
    TabLine                     = { bg = c.statusbar, fg = c.green },
    TabLineFill                 = { bg = c.statusbar },
    TabLineSel                  = { fg = c.bg, bg = c.cyan },
    Title                       = { fg = c.blue, bold = true },
    Visual                      = { bg = c.bg_visual },
    VisualNOS                   = { bg = c.bg_visual },
    WarningMsg                  = { fg = c.yellow0 },
    Whitespace                  = { fg = c.fg_gutter },
    WildMenu                    = { bg = c.bg_visual },
    WinBar                      = "StatusLine" ,
    WinBarNC                    = "StatusLineNC",
    Bold                        = { bold = true, fg = c.fg },
    Character                   = { fg = c.green },
    Constant                    = { fg = c.yellow },
    Debug                       = { fg = c.orange },
    Delimiter                   =  "Special",
    Error                       = { fg = c.red0 },
    Function                    = { fg = c.pink },
    Identifier                  = { fg = c.lightblue },
    Italic                      = { italic = true, fg = c.fg },
    Include                     = "Keyword",
    Keyword                     = { fg = c.orange, italic = opts.italic_keywords },
    Operator                    = { fg = c.red },
    PreProc                     = { fg = c.green1 },
    Special                     = { fg = c.green1 },
    Statement                   = { fg = c.orange },
    String                      = { fg = c.lightgreen, italic = opts.italic_strings }, -- left off here
    Todo                        = { bg = c.yellow, fg = c.bg },
    Type                        = { fg = c.cyan },
    Underlined                  = { underline = true },
    debugBreakpoint             = { },
    debugPC                     = { bg = c.bg_sidebar },
    dosIniLabel                 = "@property",
    helpCommand                 = { bg = c.terminal_black, fg = c.blue },
    htmlH1                      = { fg = c.magenta, bold = true },
    htmlH2                      = { fg = c.blue, bold = true },
    qfFileName                  = { fg = c.blue },
    qfLineNr                    = { fg = c.dark5 },



    LspReferenceText            = { bg = c.bg_visual, bold = true },
    LspReferenceRead            = { bg = c.bg_visual, bold = true },
    LspReferenceWrite           = { bg = c.bg_visual, bold = true },
    LspSignatureActiveParameter = { bg = c.bg_visual, bold = true },
    LspCodeLens                 = { fg = c.green },
    LspInlayHint                = { bg = c.green0, fg = c.fg },
    LspInfoBorder               = { fg = c.lightgreen, bg = c.statusbar },
    ComplHint                   = { fg = c.bg },


    DiagnosticError             = { fg = c.red0 },
    DiagnosticWarn              = { fg = c.yellow },
    DiagnosticInfo              = { fg = c.cyan0 },
    DiagnosticHint              = { fg = c.blue },
    DiagnosticUnnecessary       = { fg = c.green },
    DiagnosticVirtualTextError  = { bg = c.red, fg = c.red1 },
    DiagnosticVirtualTextWarn   = { bg = c.yellow1 },
    DiagnosticVirtualTextInfo   = { bg = c.cyan0 },
    DiagnosticVirtualTextHint   = { bg = c.blue },
    DiagnosticUnderlineError    = { underline = true, sp = c.red0, fg = c.bg, bg = c.red1 },
    DiagnosticUnderlineWarn     = { underline = true, sp = c.yellow },
    DiagnosticUnderlineInfo     = { underline = true, sp = c.cyan0 },
    DiagnosticUnderlineHint     = { underline = true, sp = c.blue },


    healthError                 = { fg = c.red },
    healthSuccess               = { fg = c.green1 },
    healthWarning               = { fg = c.yellow0 },


    diffAdded                   = { },
    diffRemoved                 = { },
    diffChanged                 = { },
    diffOldFile                 = { },
    diffNewFile                 = { },
    diffFile                    = { fg = c.blue },
    diffLine                    = { fg = c.green },
    diffIndexLine               = { fg = c.magenta },
    helpExample                 = { fg = c.green },
	}
end

return M
