local M = {}

function M.get(c, opts)
   -- stylua: ignore 
   local ret = {
    ["@annotation"]                 = "PreProc",
    ["@attribute"]                  = "PreProc",
    ["@boolean"]                    = "Boolean",
    ["@character"]                  = "Character",
    ["@character.printf"]           = "SpecialChar",
    ["@character.special"]          = "SpecialChar",
    ["@comment"]                    = "Comment",
    ["@comment.error"]              = { fg = c.red1, italic = opts.styles.comments.italic },
    ["@comment.hint"]               = { fg = c.blue, italic = opts.styles.comments.italic },
    ["@comment.info"]               = { fg = c.cyan0, italic = opts.styles.comments.italic },
    ["@comment.note"]               = { fg = c.green1, italic = opts.styles.comments.italic },
    ["@comment.todo"]               = { fg = c.blue0, italic = opts.styles.comments.italic },
    ["@comment.warning"]            = { fg = c.yellow, italic = opts.styles.comments.italic },
    ["@constant"]                   = "Constant",
    ["@constant.builtin"]           = "Constant",
    ["@constant.macro"]             = "Constant",
    ["@constructor"]                = { fg = c.cyan0 },
    ["@constructor.tsx"]            = "@constructor",
    ["@diff.delta"]                 = "DiffChange",
    ["@diff.minus"]                 = "DiffDelete",
    ["@diff.plus"]                  = "DiffAdd",
    ["@function"]                   = "Function",
    ["@function.builtin"]           = {fg = c.pink, italic = true},
    ["@function.call"]              = "@function",
    ["@function.macro"]             = {fg = c.pink},
    ["@function.macro.commonlisp"]  = "@keyword",
    ["@function.method"]            = "Function",
    ["@function.method.call"]       = "@function.method",
    ["@keyword"]                    = "Keyword",
    ["@keyword.conditional"]        = "Conditional",
    ["@keyword.coroutine"]          = "@keyword",
    ["@keyword.debug"]              = "Debug",
    ["@keyword.directive"]          = { fg = c.orange},
    ["@keyword.directive.define"]   = "Keyword",
    ["@keyword.exception"]          = "Exception",
    ["@keyword.function"]           = { fg = c.orange, italic = true },
    ["@keyword.import"]             = "Keyword",
    ["@keyword.operator"]           = "@operator",
    ["@keyword.repeat"]             = "Repeat",
    ["@keyword.return"]             = "@keyword",
    ["@keyword.storage"]            = "StorageClass",
    ["@label"]                      = { fg = c.blue },
    ["@markup"]                     = "@none",
    ["@markup.emphasis"]            = { italic = true },
    ["@markup.environment"]         = "Macro",
    ["@markup.environment.name"]    = "Type",
    ["@markup.heading"]             = "Title",
    ["@markup.italic"]              = { italic = true },
    ["@markup.link"]                = { fg = c.teal },
    ["@markup.link.label"]          = "SpecialChar",
    ["@markup.link.label.symbol"]   = "Identifier",
    ["@markup.link.url"]            = "Underlined",
    ["@markup.list"]                = { fg = c.blue5 },
    ["@markup.list.checked"]        = { fg = c.green1 },
    ["@markup.list.markdown"]       = { fg = c.orange, bold = true },
    ["@markup.list.unchecked"]      = { fg = c.blue },
    ["@markup.math"]                = "Special",
    ["@markup.quote"]               = { fg = c.gray, italic = true },
    ["@markup.raw"]                 = "String",
    ["@markup.raw.markdown_inline"] = { bg = c.bg_visual, fg = c.green1},
    ["@markup.strikethrough"]       = { strikethrough = true },
    ["@markup.strong"]              = { bold = true },
    ["@markup.underline"]           = { underline = true },
    ["@module"]                     = {fg = c.cyan},
    ["@module.builtin"]             = { fg = c.red },
    ["@namespace.builtin"]          = "@variable.builtin",
    ["@none"]                       = {},
    ["@number"]                     = "Number",
    ["@number.float"]               = "Float",
    ["@operator"]                   = "Operator",
    ["@property"]                   = { fg = c.lightblue },
    ["@punctuation.bracket"]        = { fg = c.gray },
    ["@punctuation.delimiter"]      = { fg = c.lightblue },
    ["@punctuation.special"]        = { fg = c.lightblue },
    ["@punctuation.special.markdown"] = { fg = c.lightblue },
    ["@string"]                     = "String",
    ["@string.documentation"]       = { fg = c.yellow },
    ["@string.escape"]              = { fg = c.cyan0 },
    ["@string.regexp"]              = { fg = c.blue },
    ["@tag"]                        = "Label",
    ["@tag.attribute"]              = "@property",
    ["@tag.delimiter"]              = "Delimiter",
    ["@tag.delimiter.tsx"]          = "@tag.delimiter",
    ["@tag.tsx"]                    = { fg = c.red },
    ["@tag.javascript"]             = { fg = c.red },
    ["@type"]                       = "Type",
    ["@type.builtin"]               = { fg = c.cyan },
    ["@type.definition"]            = "Typedef",
    ["@type.qualifier"]             = "@keyword",
    ["@variable"]                   = { fg = c.fg },
    ["@variable.builtin"]           = { fg = c.yellow, italic = true },
    ["@variable.member"]            = { fg = c.lightblue },
    ["@variable.parameter"]         = { fg = c.fg, italic = true },
    ["@variable.parameter.builtin"] = { },
  }

  for i, cl in ipairs(c.hfg) do
    ret["@markup.heading." .. i .. ".markdown"] = { fg = cl, bold = true }
  end

  return ret
end

return M
